apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-psql-deployment
spec:
  selector:
    matchLabels:
      name: psql-pods
  template:
    metadata:
      labels:
        name: psql-pods
    spec:
      containers:
        - name: container-psql
          image: postgres:latest
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: psql-credential
                  key: psql-password
            - name: POSTGRES_USER
              value: "vizu"
            - name: POSTGRES_DB
              value: "db_managers"
      #     volumeMounts:
      #       - name:  db-data
      #         mountPath: /var/lib/postgresql/data
      # volumes:
      #   - name: db-data
      #     hostPath:
      #       path: /data/volume-example
---
apiVersion: v1
kind: Service
metadata:
  name: psql-service
spec:
  type: ClusterIP
  selector: 
    name: psql-pods
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Secret
metadata:
  name: psql-credential
type: Opaque
data:
  psql-password: dml6dWNvZGU=