apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
spec:
  selector:
    matchLabels:
      name: user-pods
  template:
    metadata:
      labels:
        name: user-pods
    spec:
      containers:
        - name: user-container
          image: hirasakavizu/userservice
          env:
            - name: DB_USER
              value: vizu
            - name: DB_HOST
              value: "10.100.66.230"
            - name: DB_PORT
              value: "5432"
            - name: DB_DBNAME
              value: db_managers
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: psql-credential
                  key: psql-password
            - name: JWT_SECRET
              value: secret
            - name: SERVER_PORT
              value: "8081"
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  type: ClusterIP
  selector: 
    name: user-pods
  ports:
    - port: 8081
      targetPort: 8081
---
apiVersion: v1
kind: Secret
metadata:
  name: psql-credential
type: Opaque
data:
  psql-password: dml6dWNvZGU=
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-credential
type: Opaque
data:
  jwt-secret: c2VjcmV0